// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaOVACWEbN20bpZ9S-bTY40Z5rC18hjHE',
    appId: '1:688219837844:web:1f44bb38d40d673552eb81',
    messagingSenderId: '688219837844',
    projectId: 'intern-hub-355ee',
    authDomain: 'intern-hub-355ee.firebaseapp.com',
    storageBucket: 'intern-hub-355ee.appspot.com',
    measurementId: 'G-0XLE1GRHBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI5ebskk9W3wmmy0Mw85DsnQ_xxOqX61s',
    appId: '1:688219837844:android:2ddcf0e862f0926e52eb81',
    messagingSenderId: '688219837844',
    projectId: 'intern-hub-355ee',
    storageBucket: 'intern-hub-355ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYqMqV6L14OOzFJ13lYMDgl-z8gBDV6M4',
    appId: '1:688219837844:ios:2fee5944ebf4fd2552eb81',
    messagingSenderId: '688219837844',
    projectId: 'intern-hub-355ee',
    storageBucket: 'intern-hub-355ee.appspot.com',
    iosBundleId: 'com.eraa.internhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYqMqV6L14OOzFJ13lYMDgl-z8gBDV6M4',
    appId: '1:688219837844:ios:2fee5944ebf4fd2552eb81',
    messagingSenderId: '688219837844',
    projectId: 'intern-hub-355ee',
    storageBucket: 'intern-hub-355ee.appspot.com',
    iosBundleId: 'com.eraa.internhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaOVACWEbN20bpZ9S-bTY40Z5rC18hjHE',
    appId: '1:688219837844:web:1224c7d43bb86a9c52eb81',
    messagingSenderId: '688219837844',
    projectId: 'intern-hub-355ee',
    authDomain: 'intern-hub-355ee.firebaseapp.com',
    storageBucket: 'intern-hub-355ee.appspot.com',
    measurementId: 'G-CZCTCZE32K',
  );
}
